#
# Rundeck Realm Users
# Format: username:password,role1,role2,...
# Roles: user, admin, architect, deploy, build
#

admin:admin,user,admin,architect,deploy,build
dbcostops:dbcostops123,user,deploy,build
